### ISSUE TITLE
GMD 2.2 Release Backlog

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#842]
### PWA
- [ ] Update AppInstallBanner to use the new ` prompt() ` method (No more hacks) [Link](https://developers.google.com/web/fundamentals/app-install-banners/)
- [ ] Desktop PWA ( Not planned )
- [ ] Placeholder UI - recommended by PWA + UX  [Link](https://cloudcannon.com/deconstructions/2014/11/15/facebook-content-placeholder-deconstruction.html)

### Core API's
- [ ] Global Configuration Setting
- [ ] Added a way to configure Density
- [x] Markings for Mandatory fields on ` Input FIelds ` using asterisk
- [x] Support for MaterialIcon#setCustomIconType(String) 
     - [x] FontAwesomeResources import (Incubator)
     - [x] Applied to all icon structure (Tabs, SideNavs, Buttons, Link etc.)
- [ ] Scrollable Support for horizontal navigation
     - [ ] Tabs
     - [ ] Breadcrumbs
- [ ] MaterialDropdown - Apply generic ` MaterialDropdown<T> ` 
- [ ] Field Group (Under Discussion) #760
- [ ] Extra Large Screen Support (Under Discussion)  #794
- [ ] ListBox - multiple select #792
- [ ] Replaced deprecated ` Date ` class to ` LocalDateTime `
- [ ] ComboBox
     - [ ] Dropdown templating
     - [ ] Allow null option and enhance the look and feel
- [x] Dialogs
     - [x] Backdrop theming [Blur, Solid (with color) )
- [ ] Sidenav - Provide an interface to closeOnClick functionality for customization. #882
- [ ] CardTitle - Provide a description property just like MaterialTitle
- [ ] Support Selection Event to the ff:
   - [ ] SideNav
   - [ ] CollapsibleItems
   - [ ] FAB
   - [ ] TAB
- [ ]  SEO Optimizations
- [ ] SideNav - Prevent Collapsible header to apply closeOnClick feature. 
- [ ] Implement Editor<T> interface to any value widgets
- [ ] Added Overlay Style options 
   - To Configure the blur, opacity and background color of the overlay
   - Applies to
     - [x] SideNav
     - [x] Dialogs
     - [ ] Date Picker
     - [ ] Time Picker
     - [ ] Loaders
- [x] Status Field Mixin implementation + icon support
     - [x] ValueBoxes
     - [x] Input Masks
     - [x] Pickers
     - [x] ListBoxes
- [x] Focus state design update on 
     - [x] ListBox + ComboBox
     - [x] Pickers
- [ ] `setEnabledContainer` must be implemented to MaterialWidget
        
#### SASS Theming
- [x] support for custom theme
- [x] ` mvn clean package -PgenerateTheme ` (gwt-material-themes)
- [x] support dev and prod ` materialize.css ` file
- [x] added individual sass files for (override widgets, addins, incubator)

#### Async Widgets
- [x] added ` widget.setAsynchronous(true) ` to enable async support
- [x] added ` widget.setAsyncCallback(asyncCalllback, widget) ` to easily define the callback
- [x] added ` widget.success(T) ` and ` widget.failure(T) `
- [x] added ` widget.setAsyncDisplayLoader(DisplayLoader) ` to easily define the UI State (Loading, Error, Success)

#### Density Feature
- [x] Research https://material.io/design/layout/density.html#usage
- [x] Created a density enum (DEFAULT, COMFORTABLE, COMPACT)
- [x] Added support for custom density ` widget.setDensity(new DensityValue("cozy", 90)) `
   - [x] SideNav
   - [x] Table=

#### Accessibility
- [x] MaterialImage support for ` setAlt(String) `

### Style Additions
- [x] - Letter Spacing

### Addins / Incubator
- [ ] Infinite Scroll 
- [ ] Moved all existing incubator widgets to Addins
- [ ] AsynButton - Support for ` icon-only `
- [ ] Check all external libraries (addins) js releases. (If any update the version)
- [ ] ComboBox
     - supports for templating [Reference](https://github.com/GwtMaterialDesign/gwt-material-addins/issues/358)
     - supports for custom background selection for options.
     - supports for AllowBlankKey property
- [ ] Autocomplete - supports allowDuplicates option
- [ ] FileUploader - support for Header information
- [ ] RichEditor - Internalization / Language Support (If any)
- [ ] Date Range Widget
- [x] Moment Js

### Material Design 2.2
- [x] TextFields
  - [x] Outlined
  - [x] Filled 
  - [x] Left Aligned
-  [ ] Extended FAB [Link]( https://material.io/design/components/buttons-floating-action-button.html#extended-fab)
- [ ] Banners [Link]( https://material.io/design/components/banners.html)
- [x] Button 
  - [x] Outlined Type
- [x] Chips 
  - [x] Outlined Type
  - [ ] can have an error state
- [ ] Toast
   - Support for none dismissable toast with ` x ` or close icon 
- [ ] Material Design 2 Icons 
  - Study and implement a poc for the new icons. Should be added as a backlog for GMD 2.2
  - As new icon tool defined individual themes for the icons [Link](https://material.io/tools/icons/?style=round)

### Deprecations
```
his message started appearing in my Chrome console when I run my GWT/GMD based application. "[Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead." Does GMD has anything to do with it? Without doing any investigation, I'm assuming GMD is using the Element.createShadowRoot. Is my assumption correct? If yes, is there a plan to refactor GMD to use Element.attachShadow?
```

### DataTable
-  Expand table row programmatically without mouse click (#129)
